### ISSUE TITLE
[Windows] Array out of bound

### ISSUE THREAD

**Issue by chs000-00** [NeonG4/PythonWordle#14]
When running the script, the program ends in a runtime bug in the checkword function after a few repetitions of the checkword function

**Comment by NeonG4** [comment]
I'll test on my chromebook...

**Comment by NeonG4** [comment]
I ran it on replit, no bug. The score didn't show, however. It just displayed "<function checkword at 0x7fbd08b7be20>"

**Comment by NeonG4** [comment]
Alright, I fixed the "<function checckword at 0x7fbd08b7be20>" bug.

**Comment by chs000-00** [comment]
Ok, but it arrays out of bounds on my windows pc (or at least used to); I will check if it still does it though
