### ISSUE TITLE
Case check

### ISSUE THREAD

**Issue by NeonG4** [NeonG4/PythonWordle#8]
When the subroutine "checkwordgreen" runs, it has a bug. 
`
word = "hello" #example 
guess = "geese" #we only want the 2nd letter to turn green, we don't want the other e's to turn yellow"
`

**Comment by chs000-00** [comment]
For me the entire program runs into a runtime error (Array out of bounds)  
But please tell me the steps you took to get this bug

**Comment by NeonG4** [comment]
It's more of a logic error, not a bug.

**Comment by NeonG4** [comment]
> For me the entire program runs into a runtime error (Array out of bounds) But please tell me the steps you took to get this bug

Also, if you have a separate error, create a new issue. (I think I fixed it, I am using firewalledreplit.com)

**Comment by chs000-00** [comment]
How do you reproduce it?

**Comment by NeonG4** [comment]
Lets instead of choosing a random word from the word library, set it to something like "eieio", and if we type in geese, the result will be grey, yellow, green, grey, yellow. It should be grey, yellow, green, grey, grey.

**Comment by chs000-00** [comment]
OK, I see
